language: python
python:
  - "3.6"
sudo: required
services:
  - docker
before_install:
  - pip install flake8
  - flake8 *.py
  - cd Docker && make
  - make compose-detach
script:
  - echo -en "GET /health HTTP/1.0\r\n\r\n" > /dev/tcp/127.0.0.1/80 
